### ISSUE TITLE
Triangle tooltip to show more info does not show on IE11

### ISSUE THREAD

**Issue by ayaleloehr** [department-of-veterans-affairs/messaging-fe#166] opened 2016-11-14 01:19 UTC
Sorry this description isn't great, I don't know exactly what to call this triangle:

<img width="938" alt="screen shot 2016-11-13 at 8 17 46 pm" src="https://cloud.githubusercontent.com/assets/4719765/20250592/5f51412a-a9de-11e6-8b63-09c43906aa96.png">

But it seemed not to show up on IE11 when testing with a user. Can anyone replicate?

**Comment by webinista** [comment] 2016-11-22 17:53
I haven't been able to replicate this. Do you recall whether any of the other icons on the page were missing? My suspicion is that it was due to slow font loading. I'd prefer to see us use inline SVG for precisely this reason.

**Comment by ayaleloehr** [comment] 2016-11-25 21:46
I will try on IE11 on the VA network on Monday when I'm back in the office.

**Comment by webinista** [comment] 2016-12-20 21:49
Is this still an issue Alex?

**Comment by ayaleloehr** [comment] 2016-12-21 05:23
@eli-lewis can you check this in IE please? If that triangle in the image at the top of this issue shows up for you, please close.

**Comment by eli-lewis** [comment] 2017-01-04 11:56
tested in IE Edge  and confirmed that triangle image shows up.  Closing issues.
![triangle](https://cloud.githubusercontent.com/assets/23019174/21641608/f0b7933c-d24a-11e6-8f70-550a92261ec7.PNG)

**Comment by eli-lewis** [comment] 2017-01-05 19:12
tested in IE11 on VA computer and the triangle is not there.  Talked with @j-quag and he noted that this issue is present across several applications with IE11... icons on the left nav of waffle do not show, etc.  As a result, i'm not sure this is something that we can fix.  The triangle is there in other browsers and in IE Edge.  @ayaleloehr keep open or close?

**Comment by ayaleloehr** [comment] 2017-01-05 19:28
We need to come up with another way for users to see the info in this dropdown then. @angel @U-DON @bshyong any thoughts?

**Comment by webinista** [comment] 2017-01-05 19:30
Is it possible that this only affects IE11 users on VA computers or on the VA network? I've never been able to duplicate.

**Comment by bshyong** [comment] 2017-01-05 19:56
I think it's possible that this is a VA Network only problem, especially if the icons on other websites do not show as well when accessing through VA. Maybe the asset is being blocked somehow?

**Comment by eli-lewis** [comment] 2017-01-05 21:12
does anyone have IE11 on their laptops and not on the VA network?

**Comment by J-Quag** [comment] 2017-01-05 21:13
@eli-lewis  I think I do at home, I'll double check when I'm home tonight.

**Comment by jcmeloni-zz** [comment] 2017-01-05 21:15
I do.

Sent from my iPhone

On Jan 5, 2017, at 4:12 PM, eli-lewis <notifications@github.com<mailto:notifications@github.com>> wrote:


does anyone have IE11 on their laptops and not on the VA network?

-

**Comment by eli-lewis** [comment] 2017-01-05 21:52
@J-Quag & @jcmeloni awesome!  thanks!

**Comment by eli-lewis** [comment] 2017-01-06 17:20
@J-Quag and @jcmeloni any chance you tested on IE11 to see if the triangle shows up?

**Comment by jcmeloni-zz** [comment] 2018-10-27 14:11
I'm pretty sure this can be closed 2 years later as can't reproduce or won't-fix :)

**Closed as completed** 2018-10-27 15:23 UTC
Labels: ready
