### ISSUE TITLE
SM- Mobile- Messages in sub folders not showing

### ISSUE THREAD

**Issue by eli-lewis** [department-of-veterans-affairs/messaging-fe#169] opened 2016-11-15 16:23 UTC
-  Can not view any of the messages in subfolders
-  Unable to view subfolders, application gets "stuck" on the previous folder- screenshot shows two folders highlights.
- Messages in sub folders not showing
![messages in sub folders not showing](https://cloud.githubusercontent.com/assets/23019174/20313730/d17dfa20-ab25-11e6-81c4-7c8e1a94e96f.png)

**Comment by webinista** [comment] 2016-11-17 20:32
Closing as a duplicate of #177, since the problem is described in more detail there.

**Closed as completed by webinista** 2016-11-17 20:32 UTC
Labels: bug
